const data=[{name:'低層',floors:3,period:.3,height:104,color:'#78d6c6'},{name:'中層',floors:8,period:.8,height:166,color:'#58a9df'},{name:'高層',floors:15,period:1.5,height:236,color:'#8d91e8'},{name:'超高層',floors:25,period:2.5,height:304,color:'#d284c5'}];
const scene=document.querySelector('#scene'),ground=document.querySelector('#ground'),periodOut=document.querySelector('#period'),winnerOut=document.querySelector('#winner'),live=document.querySelector('#live'),guide=document.querySelector('#guide'),manualBtn=document.querySelector('#manualBtn'),sensorBtn=document.querySelector('#sensorBtn'),message=document.querySelector('#message'),power=document.querySelector('#power'),container=document.querySelector('#buildings');
let period=.8,x=0,dragging=false,mode='manual',frame,lastX=0,lastT=0,startX=0,velocity=0,direction=0,reversals=[];
const sensor={x:0,v:0,filtered:0,gravity:0,direction:0,reversals:[],last:0};
function response(t,n){const r=t/n,z=.13;return 1/Math.sqrt((1-r*r)**2+(2*z*r)**2)}
function renderBuildings(){container.innerHTML=data.map((b,i)=>`<article class="slot" data-i="${i}"><span class="badge">いちばん揺れる！</span><div class="tower-wrap" style="height:${b.height}px"><div class="tower" style="height:${b.height}px;--color:${b.color}"><div class="windows">${'<i></i>'.repeat(Math.min(b.floors*2,24))}</div></div></div><div class="label"><b>${b.name}</b><small>${b.floors}階建て</small></div><span class="chip">固有周期 <b>${b.period.toFixed(1)}秒</b></span><div class="meter"><span>揺れ</span><i style="--color:${b.color}"><b></b></i><strong></strong></div></article>`).join('');update()}
function update(){const values=data.map(b=>response(period,b.period)),win=values.indexOf(Math.max(...values));document.querySelectorAll('.slot').forEach((el,i)=>{const n=Math.min(1,values[i]/3.9);el.classList.toggle('win',i===win);el.querySelector('.tower').style.transform=`translateX(${x}px) skewX(${(-x*n)/7}deg)`;el.querySelector('.meter b').style.width=`${Math.max(8,n*100)}%`;el.querySelector('.meter strong').textContent=values[i].toFixed(1)});ground.style.transform=`translateX(${x}px)`;periodOut.firstChild.textContent=period.toFixed(1);winnerOut.textContent=`${data[win].name}の建物`}
function setPeriod(v){period=Math.min(3,Math.max(.2,v));update()}
scene.addEventListener('pointerdown',e=>{if(mode==='sensor')return;cancelAnimationFrame(frame);dragging=true;scene.classList.add('dragging');scene.setPointerCapture(e.pointerId);startX=e.clientX-x;lastX=e.clientX;lastT=e.timeStamp;velocity=0;reversals=[];live.classList.add('on');live.querySelector('b').textContent='操作中'});
scene.addEventListener('pointermove',e=>{if(!dragging||mode==='sensor')return;const dt=Math.max(8,e.timeStamp-lastT),v=(e.clientX-lastX)/dt,dir=Math.sign(v);if(dir&&direction&&dir!==direction&&Math.abs(v)>.04){reversals.push(e.timeStamp);reversals=reversals.slice(-4);if(reversals.length>=3)setPeriod((reversals.at(-1)-reversals.at(-3))/1000)}if(dir)direction=dir;velocity=v;lastX=e.clientX;lastT=e.timeStamp;x=Math.max(-48,Math.min(48,e.clientX-startX));update()});
function release(e){if(!dragging)return;dragging=false;scene.classList.remove('dragging');scene.releasePointerCapture(e.pointerId);live.classList.remove('on');live.querySelector('b').textContent='地面を左右に動かそう';const began=performance.now(),initial=x,kick=Math.max(12,Math.min(46,Math.abs(velocity)*90)),sign=velocity>=0?1:-1,duration=Math.max(.25,period)*1000;function animate(now){const t=now-began,decay=Math.exp(-t/1450);x=(initial*Math.cos(t/duration*Math.PI*2)+sign*kick*Math.sin(t/duration*Math.PI*2))*decay;update();if(decay>.035)frame=requestAnimationFrame(animate);else{x=0;update()}}frame=requestAnimationFrame(animate)}scene.addEventListener('pointerup',release);scene.addEventListener('pointercancel',release);
manualBtn.addEventListener('click',()=>{mode='manual';manualBtn.classList.add('active');sensorBtn.classList.remove('active');message.textContent='ゆっくり・速く、往復のリズムを変えてみよう';guide.innerHTML='<strong>↔</strong><span><b>地面をつかんで、左右に揺らす</b><small>スマホでは画面を左右にスワイプ</small></span>';live.classList.remove('on');x=0;sensor.v=0;update()});
sensorBtn.addEventListener('click',async()=>{if(!('DeviceMotionEvent'in window)){message.textContent='この端末はモーションセンサーに対応していません';return}try{sensorBtn.disabled=true;const result=typeof DeviceMotionEvent.requestPermission==='function'?await DeviceMotionEvent.requestPermission():'granted';if(result!=='granted')throw Error();mode='sensor';sensorBtn.classList.add('active');manualBtn.classList.remove('active');message.textContent='端末をしっかり持ち、左右へ安全に振ってください';guide.innerHTML='<strong>◉</strong><span><b>スマホを左右に振ってみよう</b><small>落とさないよう、しっかり持って操作してください</small></span>';live.classList.add('on');live.querySelector('b').textContent='センサー計測中'}catch{message.textContent='センサーが許可されませんでした。ブラウザー設定をご確認ください'}finally{sensorBtn.disabled=false}});
window.addEventListener('devicemotion',e=>{if(mode!=='sensor')return;const now=performance.now(),dt=Math.min(.05,Math.max(.008,sensor.last?(now-sensor.last)/1000:.016));sensor.last=now;const angle=screen.orientation?.angle||0,lin=e.acceleration,g=e.accelerationIncludingGravity;let raw=0;if(lin&&(lin.x!==null||lin.y!==null))raw=Math.abs(angle)===90?(lin.y||0):(lin.x||0);else if(g){const axis=Math.abs(angle)===90?(g.y||0):(g.x||0);sensor.gravity=sensor.gravity*.94+axis*.06;raw=axis-sensor.gravity}sensor.filtered=sensor.filtered*.72+raw*.28;const a=Math.abs(sensor.filtered)<.16?0:sensor.filtered;sensor.v=(sensor.v+a*dt*64-sensor.x*dt*2.2)*.94;sensor.x=Math.max(-48,Math.min(48,sensor.x+sensor.v*dt));if(Math.abs(sensor.x)>=47)sensor.v*=-.28;x=sensor.x;power.style.width=`${Math.min(100,Math.abs(a)/5*100)}%`;const dir=Math.sign(a);if(dir&&sensor.direction&&dir!==sensor.direction&&Math.abs(a)>.45){sensor.reversals.push(now);sensor.reversals=sensor.reversals.slice(-5);if(sensor.reversals.length>=3)setPeriod((sensor.reversals.at(-1)-sensor.reversals.at(-3))/1000)}if(dir)sensor.direction=dir;update()});
renderBuildings();
